listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

http_listener:
  tcp:
    address: 0.0.0.0
    port: 8081
    secure: false

logger:
  pretty: true
  level: DEBUG

database:
  auth_method: 2
  host: ${DATABASE_HOST}
  port: 3306
  name: ${DATABASE_NAME}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  aws_region: ${DATABASE_AWS_REGION}
  debug: false
  tracing_enabled: false
  max_idle_conns: 5

redis:
  address: ${REDIS_ADDRESS}
  namespace: ${REDIS_NAMESPACE}

auth:
  AccessKey: ${AUTH_ACCESS_KEY}
  AccessExp: 90
  RefreshKey: ${AUTH_REFRESH_KEY}
  RefreshExp: 120

google:
  ClientID: ${GOOGLE_CLIENT_ID}

frontend:
  Url: "http://skillsharp.software"
  ResetPasswordEndpoint: "/auth/new-password"

mailer:
  Domain: "http://twistedfate:8080"
  Endpoint: "/twistedfate/mailer/send"
