listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

http_listener:
  tcp:
    address: 0.0.0.0
    port: 8081
    secure: false

logger:
  pretty: true
  level: DEBUG

rabbitmq: 
  address: 10.148.0.11
  port: 5672  
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  consume_queue: consume_queue
  public_queue: public_queue
  max_consumer: 5
  expire_time: 86400000

database:
  auth_method: ${DATABASE_AUTH_METHOD}
  host: ${DATABASE_HOST}
  port: 3306
  name: ${DATABASE_NAME}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  aws_region: ${DATABASE_AWS_REGION}
  debug: false
  tracing_enabled: false
  max_idle_conns: 5

redis:
  address: ${REDIS_ADDRESS}
  namespace: ${REDIS_NAMESPACE}
